const L=[
{id:'origine',ic:'🌱',n:'Origine',q:"D'où est-ce que je viens ?",
 p:[["Genèse 1.27","DIEU créa l'homme à son image, il le créa à l'image de DIEU, il créa l'homme et la femme."],["Psaume 139.13-14","C'est toi qui as formé mes reins, qui m'as tissé dans le sein de ma mère. Je te loue de ce que je suis une créature si merveilleuse."]],
 r:"Si DIEU est à l'origine de ta vie, qu'est-ce que cela change dans ta manière de voir ta vie ?",
 z:[["Selon Genèse 1, l'être humain est créé…",["par hasard","à l'image de DIEU","par ses propres efforts"],1],["Vrai ou faux : ma valeur dépend de mes réussites.",["Vrai","Faux"],1],["Un ami se sent « inutile ». Quelle vérité de ce niveau pourrait l'aider ?",["Il est le fruit d'une volonté de DIEU","Il doit prouver sa valeur","Il doit se comparer aux autres"],0]],
 s:"Je n'existe pas par accident. DIEU est à l'origine de ma vie."},
{id:'relation',ic:'❤️',n:'Relation',q:"Qui est DIEU pour moi ?",
 p:[["Jean 17.3","Or, la vie éternelle, c'est qu'ils te connaissent, toi, le seul vrai DIEU, et celui que tu as envoyé, YESHUA'H-Christ."],["Psaume 23.1","L'Éternel est mon berger : je ne manquerai de rien."]],
 r:"Quand tu penses à DIEU, quelle image as-tu de lui ? D'où vient-elle ?",
 z:[["Selon Jean 17.3, la vie éternelle, c'est…",["accumuler des connaissances","connaître DIEU et YESHUA'H-Christ","respecter des règles"],1],["Vrai ou faux : DIEU est décrit comme un berger qui prend soin de moi.",["Vrai","Faux"],0],["Tu traverses un manque. Comment le Psaume 23 t'invite-t-il à regarder DIEU ?",["Comme un juge distant","Comme un berger qui pourvoit","Comme une idée abstraite"],1]],
 s:"DIEU n'est pas lointain : il désire une relation personnelle avec moi."},
{id:'identite',ic:'🪞',n:'Identité',q:"Qui suis-je ?",
 p:[["Éphésiens 2.10","Car nous sommes son ouvrage, ayant été créés en YESHUA'H-Christ pour de bonnes œuvres."],["1 Pierre 2.9","Vous, au contraire, vous êtes une race élue, un sacerdoce royal, une nation sainte, un peuple acquis."]],
 r:"Quelles étiquettes (du monde, des autres, de toi-même) te définissent aujourd'hui ? Lesquelles sont à remettre en question ?",
 z:[["Éphésiens 2.10 dit que nous sommes…",["son ouvrage","un accident","des spectateurs"],0],["Vrai ou faux : mon identité se construit d'abord par le regard des autres.",["Vrai","Faux"],1],["Après un échec, tu te dis « je suis nul ». Que fais-tu ?",["Je confronte cette pensée à ce que DIEU dit de moi","Je l'accepte","Je l'ignore"],0]],
 s:"Mon identité est reçue de DIEU, elle ne se gagne pas."},
{id:'statut',ic:'📜',n:'Statut',q:"Quelle est ma condition devant DIEU ?",
 p:[["Romains 3.23","Car tous ont péché et sont privés de la gloire de DIEU."],["Romains 5.8","Mais DIEU prouve son amour envers nous, en ce que, lorsque nous étions encore des pécheurs, Christ est mort pour nous."]],
 r:"Qu'est-ce qui est difficile - ou libérateur - dans le fait de reconnaître sa propre condition devant DIEU ?",
 z:[["Selon Romains 3.23, qui a péché ?",["Seulement les autres","Tous","Personne"],1],["Vrai ou faux : Christ est mort pour nous après que nous nous sommes améliorés.",["Vrai","Faux"],1],["Pourquoi Romains 5.8 est-il une bonne nouvelle ?",["L'amour de DIEU précède mon mérite","Je dois d'abord me corriger","Le péché n'existe pas"],0]],
 s:"J'ai besoin de grâce, et DIEU me l'a donnée avant que je la mérite."},
{id:'position',ic:'👑',n:'Position',q:"Quelle place ai-je en Christ ?",
 p:[["Romains 8.1","Il n'y a donc maintenant aucune condamnation pour ceux qui sont en YESHUA'H-Christ."],["Éphésiens 2.6","Il nous a ressuscités ensemble, et nous a fait asseoir ensemble dans les lieux célestes en YESHUA'H-Christ."]],
 r:"Dans quelles situations te sens-tu condamné ? Que dit Romains 8.1 à ces moments-là ?",
 z:[["Romains 8.1 déclare…",["aucune condamnation en Christ","une condamnation permanente","une condamnation partielle"],0],["Vrai ou faux : ma position en Christ dépend de mes performances du jour.",["Vrai","Faux"],1],["Tu te sens indigne de prier. Que rappelles-tu ?",["Je suis en Christ, j'ai accès à DIEU","Je prierai quand je serai meilleur","DIEU est fâché"],0]],
 s:"Je suis en Christ : accepté, sans condamnation, à la place qu'il m'a donnée."},
{id:'heritage',ic:'🎁',n:'Héritage',q:"Qu'est-ce qui m'est donné et réservé en Christ ?",
 p:[["Romains 8.17","Et si nous sommes enfants, nous sommes aussi héritiers : héritiers de DIEU, et cohéritiers de Christ."],["1 Pierre 1.4","Pour un héritage qui ne peut ni se corrompre, ni se souiller, ni se flétrir, réservé dans les cieux pour vous."]],
 r:"Comment l'espérance d'un héritage réservé peut-elle changer ta façon de vivre aujourd'hui ?",
 z:[["Selon Romains 8.17, nous sommes…",["des serviteurs sans droits","héritiers avec Christ","des invités temporaires"],1],["Vrai ou faux : l'héritage décrit en 1 Pierre 1.4 peut se corrompre.",["Vrai","Faux"],1],["Face à une épreuve, comment l'héritage t'aide-t-il ?",["Il donne une espérance solide","Il supprime toute difficulté","Il est sans rapport avec ma vie"],0]],
 s:"Ce que DIEU me réserve en Christ est sûr et durable : je vis avec espérance."}
];
