const L=[
{id:"origine",
 ic:"🌱",
 n:"Origine",
 q:"D'où est-ce que je viens ?",
 p:[["Genèse 1.27", "DIEU créa l'homme à SON image, IL le créa à l'image de DIEU, IL créa l'homme et la femme."], ["Psaume 139.13-14", "C'est TOI qui as formé mes reins, qui m'as tissé dans le sein de ma mère. Je TE loue de ce que je suis une créature si merveilleuse."]],
 r:"Si DIEU est à l'origine de ta vie, comment cela change-t-il ta manière de te voir et de considérer ton existence ?",
 d:["Suis-je simplement le résultat d'une existence biologique ?", "Ma vie a-t-elle une origine et une intention ?", "Est-ce que je m'appartiens entièrement ?"],
 rl:"Si DIEU est à l'origine de ta vie, qu'est-ce que cela change dans ta façon de considérer ton existence ?",
 z:[["Selon Genèse 1, l'être humain est créé…", ["par hasard", "à l'image de DIEU", "par ses propres efforts"], 1], ["Vrai ou faux : ma valeur dépend de mes réussites.", ["Vrai", "Faux"], 1], ["Un ami se sent « inutile ». Quelle vérité de ce niveau pourrait l'aider ?", ["Il est le fruit d'une volonté de DIEU", "Il doit prouver sa valeur", "Il doit se comparer aux autres"], 0]],
 s:"Je n'existe pas par accident. DIEU est à l'origine de ma vie."},
{id:"relation",
 ic:"❤️",
 n:"Relation",
 q:"Qui est DIEU pour moi ?",
 p:[["Jean 17.3", "Or, la vie éternelle, c'est qu'ils TE connaissent, TOI, le seul vrai DIEU, et celui que TU as envoyé, YESHUA’H."], ["Psaume 23.1", "L'Éternel est mon berger : je ne manquerai de rien."]],
 r:"Si DIEU désire être connu et établir une relation avec toi, comment cela change-t-il ta manière de LE considérer ?",
 d:["Est-ce que je connais réellement DIEU ou seulement ce que j'ai entendu dire de LUI ?", "Quelle image de DIEU influence ma manière de m'approcher de LUI ?", "Peut-on entretenir une relation avec quelqu'un que l'on ne cherche pas à connaître ?"],
 rl:"À la lumière de ces questions, comment décrirais-tu aujourd'hui ta relation avec DIEU ?",
 z:[["Selon Jean 17.3, la vie éternelle, c'est…", ["accumuler des connaissances", "connaître DIEU et YESHUA’H", "respecter des règles"], 1], ["Vrai ou faux : DIEU est décrit comme un berger qui prend soin de moi.", ["Vrai", "Faux"], 0], ["Tu traverses un manque. Comment le Psaume 23 t'invite-t-il à regarder DIEU ?", ["Comme un juge distant", "Comme un berger qui pourvoit", "Comme une idée abstraite"], 1]],
 s:"DIEU n'est pas lointain : IL désire une relation personnelle avec moi."},
{id:"identite",
 ic:"🪞",
 n:"Identité",
 q:"Qui suis-je ?",
 p:[["Éphésiens 2.10", "Car nous sommes SON ouvrage, ayant été créés en YESHUA’H pour de bonnes œuvres."], ["1 Pierre 2.9", "Vous, au contraire, vous êtes une race élue, un sacerdoce royal, une nation sainte, un peuple acquis."]],
 r:"Si ton identité se découvre en CHRIST, qu'est-ce que cela change dans la manière dont tu te définis ?",
 d:["Qui suis-je lorsque je ne me définis plus par mes réussites ou mes échecs ?", "Les regards des autres déterminent-ils réellement mon identité ?", "Qu'est-ce que DIEU dit de moi que je n'ai peut-être jamais considéré ?"],
 rl:"À la lumière de ce que tu découvres en CHRIST, comment te définirais-tu désormais ?",
 z:[["Éphésiens 2.10 dit que nous sommes…", ["SON ouvrage", "un accident", "des spectateurs"], 0], ["Vrai ou faux : mon identité se construit d'abord par le regard des autres.", ["Vrai", "Faux"], 1], ["Après un échec, tu te dis « je suis nul ». Que fais-tu ?", ["Je confronte cette pensée à ce que DIEU dit de moi", "Je l'accepte", "Je l'ignore"], 0]],
 s:"Mon identité est reçue de DIEU, elle ne se gagne pas."},
{id:"statut",
 ic:"📜",
 n:"Statut",
 q:"Quelle est ma condition devant DIEU ?",
 p:[["Romains 3.23", "Car tous ont péché et sont privés de la gloire de DIEU."], ["Romains 5.8", "Mais DIEU prouve SON amour envers nous, en ce que, lorsque nous étions encore des pécheurs, CHRIST est mort pour nous."]],
 r:"Si tous ont péché et que CHRIST est mort pour nous alors que nous étions encore pécheurs, qu'est-ce que cela révèle sur ta condition et sur l'amour de DIEU ?",
 d:["Puis-je réellement me justifier devant DIEU par mes propres mérites ?", "Pourquoi aurais-je besoin de la grâce si je pouvais me rendre juste moi-même ?", "Que révèle la mort de CHRIST sur la manière dont DIEU me considère malgré ma condition ?"],
 rl:"Comment la grâce de DIEU change-t-elle ta compréhension de ta condition devant LUI ?",
 z:[["Selon Romains 3.23, qui a péché ?", ["Seulement les autres", "Tous", "Personne"], 1], ["Vrai ou faux : CHRIST est mort pour nous après que nous nous sommes améliorés.", ["Vrai", "Faux"], 1], ["Pourquoi Romains 5.8 est-il une bonne nouvelle ?", ["L'amour de DIEU précède mon mérite", "Je dois d'abord me corriger", "Le péché n'existe pas"], 0]],
 s:"J'ai besoin de grâce, et DIEU me l'a donnée avant que je la mérite."},
{id:"position",
 ic:"👑",
 n:"Position",
 q:"Quelle place ai-je en CHRIST ?",
 p:[["Romains 8.1", "Il n'y a donc maintenant aucune condamnation pour ceux qui sont en YESHUA’H."], ["Éphésiens 2.6", "IL nous a ressuscités ensemble, et nous a fait asseoir ensemble dans les lieux célestes en YESHUA’H."]],
 r:"Si tu es en CHRIST, comment cela change-t-il ta manière de te considérer devant DIEU ?",
 d:["Ma place devant DIEU dépend-elle de mes performances quotidiennes ?", "Quelle différence existe-t-il entre me sentir condamné et être sans condamnation en CHRIST ?", "Comment cette position influence-t-elle ma manière de m'approcher de DIEU ?"],
 rl:"Si DIEU t'a donné une position en CHRIST, comment cela devrait-il influencer ta manière de vivre et de t'approcher de LUI ?",
 z:[["Romains 8.1 déclare…", ["aucune condamnation en CHRIST", "une condamnation permanente", "une condamnation partielle"], 0], ["Vrai ou faux : ma position en CHRIST dépend de mes performances du jour.", ["Vrai", "Faux"], 1], ["Tu te sens indigne de prier. Que rappelles-tu ?", ["Je suis en CHRIST, j'ai accès à DIEU", "Je prierai quand je serai meilleur", "DIEU est fâché"], 0]],
 s:"Je suis en CHRIST : accepté, sans condamnation, à la place qu'IL m'a donnée."},
{id:"heritage",
 ic:"🎁",
 n:"Héritage",
 q:"Qu'est-ce qui m'est donné et réservé en CHRIST ?",
 p:[["Romains 8.17", "Et si nous sommes enfants, nous sommes aussi héritiers : héritiers de DIEU, et cohéritiers de CHRIST."], ["1 Pierre 1.4", "Pour un héritage qui ne peut ni se corrompre, ni se souiller, ni se flétrir, réservé dans les cieux pour vous."]],
 r:"Si tu es enfant de DIEU et héritier avec CHRIST, comment cette vérité change-t-elle ta manière de vivre aujourd'hui ?",
 d:["Quelle différence existe-t-il entre travailler pour obtenir une place et vivre à partir d'une place reçue ?", "Mon avenir est-il uniquement déterminé par ce que je possède aujourd'hui ?", "Comment l'espérance de mon héritage influence-t-elle mes choix présents ?"],
 rl:"Sachant ce qui t'est donné et réservé en CHRIST, qu'est-ce que cela change dans ta manière de vivre aujourd'hui ?",
 z:[["Selon Romains 8.17, nous sommes…", ["des serviteurs sans droits", "héritiers avec CHRIST", "des invités temporaires"], 1], ["Vrai ou faux : l'héritage décrit en 1 Pierre 1.4 peut se corrompre.", ["Vrai", "Faux"], 1], ["Face à une épreuve, comment l'héritage t'aide-t-il ?", ["Il donne une espérance solide", "Il supprime toute difficulté", "Il est sans rapport avec ma vie"], 0]],
 s:"Ce que DIEU me réserve en CHRIST est sûr et durable : je vis avec espérance."}
];
